### ISSUE TITLE
Splatmesh disappears when getting within certain radius of location

### ISSUE THREAD

**Issue by IsaacBerman** [zappar-xr/three-gaussian-splat#2]
Thanks so much for this package. It works so far, and I've integrated it into my project. However, when I get to close to the center of the splat mesh, the mesh disappears, do you know what could be causing this and could you point me in the right direction for a fix? Thanks.

**Comment by nyan-left** [comment]
Hi @IsaacBerman,

I suspect it's frustum culling kicking in when the camera is close to the object. 

You can [disable frustum culling](https://threejs.org/docs/#api/en/core/Object3D.frustumCulled) on the splat to work around this. 
 


You could also try calling `computeBoundingBox` after the splat has finished loading.

**Comment by IsaacBerman** [comment]
You're correct, thank you. Disabling frustum culling works!

**Comment by nyan-left** [comment]
Great! 

Feel free to reach out if you run into any other issues 🙂
