### ISSUE TITLE
Intersections with GaussianSplatMesh

### ISSUE THREAD

**Issue by IsaacBerman** [zappar-xr/three-gaussian-splat#3]
I was wondering if there was any compatibility with raycasting/intersecting with the GaussianSplatMesh, like is currently supported in THREE.js for Object3D types. 

Thank you in advance!

**Comment by nyan-left** [comment]
Hi @IsaacBerman,

Unfortunately, traditional THREE.js raycasters aren't compatible with `InstancedBufferGeometry`. Here are a couple of alternatives you might consider:
- Use an invisible mesh as a 'hitbox'; scale it to align with your splat and check for raycaster intersections against this mesh.
- GPU Picking as shown in this example: https://threejs.org/examples/?q=interactive#webgl_interactive_cubes_gpu

The GPU Picking approach may require a good understanding of how this repo works, so I would advise the first option :)

**Comment by IsaacBerman** [comment]
@nyan-left, yes -- invisible hit box is what I was looking at exploring. Thanks!
